replicaCount: 1

image:
  repository: ghcr.io/spaxqwii/product-service
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: ghcr-secret

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

serviceAccount:
  create: false
  name: ""

database:
  secretName: product-db-secret

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 20

ingress:
  enabled: true
  ingressClassName: nginx
  host: product-service.myapp.local
  tls:
    enabled: false
    secretName: product-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

migrate:
  image:
    repository: ghcr.io/spaxqwii/product-service-migrate
    tag: latest
