replicaCount: 1

image:
  repository: ghcr.io/spaxqwii/product-service
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: ghcr-secret

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  secretName: product-db-secret

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 20

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 40

ingress:
  enabled: true
  ingressClassName: nginx
  host: product-service.myapp.local
  tls:
    enabled: false
    secretName: product-tls

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

nodeSelector: {}
tolerations: []
affinity: {}

migrateImage:
    repository: ghcr.io/spaxqwii/product-service-migrate
    tag: latest
    pullPolicy: IfNotPresent
