apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: product-db-secret
  namespace: myapp
spec:
  encryptedData:
    DATABASE_URL: AgBLf2ujWUWU1hb0A720TEmYxEqFqqfNiEM/fIT2iZXFiqTQQsZR2xtFfMw1uhZZOMi/4MYQptjK8dE0+xs7hJbhIaCFoX6ZOAMk21NLNq/a/z04UelFkk/mav5XmLVHyvqEvSkyq6lDQYOoV9uMEPB58CjfIKVkHdcmeQLOjrbCUIwB1dmayoFa78cL5nzwrNChedpx1Np49Rq1ZD8PfTVbR872ShAj0S+z76Q432j5v1Z8ikWR0KfQ6b7OLocVIBux5jNBkH6BLrlAuD26MqKvvOZRHjxxkCpnrpxEVxYTrvijZs0s0yW3RBIQnTSFgKPDqZM3vMXpyh/EnKojjXcgQF8k4Ay0rW6iLzDG54MRHHy8c0w3ZQDjsDtBEPStNBnK0yE62vtR3ZAR47V+d9+kl8ib3p7F8JhypUJXFMZcd3tzz48yizqZTqSKK4fIgjnDlL/u6Q2vsUqRnzAIlWwL74aXLgAxAqmwJ5cRyA72p2E5CAvKNsCiPCCRXXeAnpLQUFzfwekO7EdDOEp+SaL0dD9jg56EvP5zRvByGbIoG1D7OD3OrHhhCBid07ReXkra2TRiCOQyE7H8QTvv82lc4ke0AIIIhhU6iu1uJtvV6Ar7dE9KnHTBMSweq84aENh9Sgf2r3GWcdfhB6LGke9+/4/pk09hS85puMJZhRwrPOvc774AIDsnf+WjnG2vb5nWKhz8Pwx5iwLHWVMVat6iZsT+Cjpv4a7In8iGc5lRQvhUXScFkv4nlpx4NL5wTxpmKfvUl2WuQ79cjmasyPptfNBo457Pl2MxfOl4rfskxiWxdf5VBonaPe5d3CX0yG8pbsibYujO2SrEMw==
  template:
    metadata:
      creationTimestamp: null
      name: product-db-secret
      namespace: myapp
    type: Opaque
---
