replicaCount: 1

image:
  repository: spaxqwii/user-service-migrate
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: ghcr-secret  #default name of the secret you created
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
database:
  host: postgres-postgresql.myapp.svc.cluster.local
  port: 5432
  name: users
  secretName: user-db-secret

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 20

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: user-service.myapp.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 8080
  tls:
    enabled: false
    secretName: user-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

