replicaCount: 1

image:
  repository: ghcr.io/spaxqwii/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  host: user.local
  tls:
    enabled: false
    secretName: user-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

