replicaCount: 1

image:
  repository: ghcr.io/spaxqwii/user-service
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: ghcr-secret  #default name of the secret you created
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /
  initialDelaySeconds: 15
  periodSeconds: 20

ingress:
  enabled: true
  ingressClassName: nginx
  host: user.local
  tls:
    enabled: false
    secretName: user-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

