apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    app: {{ include "user-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "user-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "user-service.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | default "ghcr-secret" }}
      containers:
        - name: {{ include "user-service.name" . }}
          image: ghcr.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
         # env:
         #   - name: DB_HOST
         #     value: {{ .Values.database.host | quote }}
         #   - name: DB_PORT
         #     value: {{ .Values.database.port | quote }}
         #   - name: DB_USER
         #     valueFrom:
         #       secretKeyRef:
         #         name: {{ .Values.database.secretName }}
         #         key: DB_USER
         #   - name: DB_PASSWORD
         #     valueFrom:
         #       secretKeyRef:
         #         name: {{ .Values.database.secretName }}
         #         key: DB_PASSWORD
         #   - name: DB_NAME
         #     value: {{ .Values.database.name | quote }}
         # - name: DATABASE_URL
         #   valueFrom:
           #     secretKeyRef:
           #       name: {{ .Values.database.secretName }}
           #       key: DATABASE_URL
          envFrom:
            - secretRef:
                name: {{ .Values.database.secretName }}
