apiVersion: batch/v1
kind: Job
metadata:
  name: user-service-migrate
  labels:
    app: user-service
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "migrate"]
          envFrom:
            - secretRef:
                name: {{ .Values.database.secretName }}
