apiVersion: batch/v1
kind: Job
metadata:
  name: user-service-migrate
  labels:
    app: user-service
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image:
            repository: {{ .Values.image.repository }}-migrate
            tag: {{ .Values.image.tag }}
          command: ["npm", "run", "migrate:up"]
          envFrom:
            - secretRef:
                name: {{ .Values.database.secretName }}
