{{- if or (.Values.migrateOnly) (not .Release.IsInstall) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "user-service.fullname" . }}-migrate
  labels:
    app: {{ include "user-service.name" . }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}"
          imagePullPolicy: {{ .Values.migrate.image.pullPolicy }}
          command: ["npx", "node-pg-migrate", "up"]
          envFrom:
            - secretRef:
                name: {{ .Values.database.secretName }}
{{- end }}